#ifndef SMARTMULTIEFFECT_EFFECTSCONTROLLER_GLOBAL_H
#define SMARTMULTIEFFECT_EFFECTSCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMARTMULTIEFFECT_EFFECTSCONTROLLER_LIBRARY)
#  define SMARTMULTIEFFECT_EFFECTSCONTROLLER_EXPORT Q_DECL_EXPORT
#else
#  define SMARTMULTIEFFECT_EFFECTSCONTROLLER_EXPORT Q_DECL_IMPORT
#endif

#endif // SMARTMULTIEFFECT_EFFECTSCONTROLLER_GLOBAL_H
